# This config file is meant for site and build settings affecting the entire blog, values that are rarely edited.
# Change are not reflected automatically and `jekyl serve` has to be restarted manually.

# Site settings
# Custom key-value pairs can be specified here as well, e.g. email: example@example.com, twitter_username: example, etc.
# For multiline values (with line breaks) prepend  `> `, e.g. description: > …
title: dec2bin.py
description: 2019 dec2bin Thecarisma # appears in head meta (for search engines) and in the feed.xml site description.
baseurl: "/dec2bin" # the subpath of your site, e.g. /blog (forward slash prefix required)
url: "https://quickutils.github.io" # the base url for your site, e.g. http://example.com
permalink: /:path # use filename as URL for posts, e.g. 2010-01-01-foo.md -> example.com/foo (also for pages)

collections:
  dec2bin:
    output: true
    permalink: /:path

defaults:
  - scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: page

# Build settings
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  auto_ids: true
  syntax_highlighter: rouge

social_media:
  - id: 'iamthecarisma'
    href: 'https://www.twitter.com/iamthecarisma'
    title: 'Twitter'
    
  - id: 'dec2bin'
    href: 'https://github.com/quickutils/dec2bin'
    title: 'Github'
    
external_links:
    - name: Azeez Adewale
      href: https://thecarisma.github.io/
      title: Azeez Adewale
      
    - name: Python
      href: https://www.python.org/
      title: Python
      
    - name: The Art Of Assembly
      href: https://www.amazon.com/Art-Assembly-Language-2nd/dp/1593272073
      title: The Art Of Assembly

# For a poor man's static archival deployment with relative links,
# change baseurl to ".", uncomment permalink, and suffix collections > dec2bin > permalink with ".html".
# Note that in-article relative links won't work and videos won't properly embed when opening via "file:///.

# Example of an FTP deployment (copy generated files in _site/ to public_html/dec2bin):
# baseurl: "/~schaad/dec2bin"
# url: "http://web.media.mit.edu"

# Example of a GH Pages deployment (sources pushed to repo "dec2bin", branch "gh-pages"):
# baseurl: "/dec2bin"
# url: "https://quickutils.github.io"
